---
- name: Label worker nodes as storage nodes
  command: oc label nodes worker-{{ item.worker }}.okd.example.com role=storage-node
  with_items:
    - { worker: '0' }
    - { worker: '1' }
    - { worker: '2' }

- name: Publish temporary manifests
  template:
    src: '{{ item.file }}.j2'
    dest: /tmp/{{ item.file }}
  with_items:
    - { file: 'common.yml' }
    - { file: 'operator.yml' }

- name: Apply manifests
  command: oc apply -f /tmp/{{ item.file }}
  with_items:
    - { file: 'common.yml' }
    - { file: 'operator.yml' }

- name: Cleanup
  file:
    path: /tmp/{{ item.file }}
    state: absent
  with_items:
    - { file: 'common.yml' }
    - { file: 'operator.yml' }
