---
- name: Create directory
  file:
    path: /usr/share/nginx/html/fcos/{{ _okd_lab_install_name }}
    state: directory

- name: Mirror Fedora CoreOS
  get_url:
    url: '{{ _okd_lab_fedora_coreos_base_url }}{{ item.file }}'
    dest: /usr/share/nginx/html/fcos/{{ _okd_lab_install_name }}/{{ item.dest }}
  with_items:
    - { file: 'metal.x86_64.raw.xz', dest: 'install.xz' }
    - { file: 'metal.x86_64.raw.xz.sig', dest: 'install.xz.sig' }
    - { file: 'live-kernel-x86_64', dest: 'vmlinuz' }
    - { file: 'live-initramfs.x86_64.img', dest: 'initrd' }

- name: Publish PXE's  
  template:
    src: '{{ item.file }}.j2'
    dest: /var/lib/tftpboot/{{ item.file }}
  with_items:
    - { file: '52-54-00-7f-0e-c5' }
    - { file: '52-54-00-9f-f8-1c' }
    - { file: '52-54-00-19-6b-b4' }
    - { file: '52-54-00-94-21-a1' }
    - { file: '52-54-00-bb-dd-78' }
    - { file: '52-54-00-da-a9-27' }
    - { file: '52-54-00-f7-84-c9' }
