---
- name: Check Repository {{ _okd_lab_install_name }} exsits?
  uri: 
    url: '{{ _okd_lab_quay_api_base_url }}/repository/kubeadmin/{{ _okd_lab_install_name }}'
    method: GET
    validate_certs: no
    return_content: yes
    headers:
      Authorization: Bearer {{lookup('file', '~/okd-lab/.secrets/bearer')}}
  register: _repo_response
  ignore_errors: yes

- name: Remove Repository {{ _okd_lab_install_name }}
  uri: 
    url: '{{ _okd_lab_quay_api_base_url }}/repository/kubeadmin/{{ _okd_lab_install_name }}'
    method: DELETE
    validate_certs: no
    return_content: yes
    headers:
      Authorization: Bearer {{lookup('file', '~/okd-lab/.secrets/bearer')}}
    status_code: '204'
  when: _repo_response.status == 200

- name: Create Repository {{ _okd_lab_install_name }}
  uri: 
    url: '{{ _okd_lab_quay_api_base_url }}/repository'
    method: POST
    validate_certs: no
    return_content: yes
    headers:
      Authorization: Bearer {{lookup('file', '~/okd-lab/.secrets/bearer')}}
    status_code: '201'
    body: "{{ lookup('template','repo.json.j2') }}"
    body_format: json


- name: Mirror Registry from {{ _okd_lab_install_mirror_from }}:{{ okd_lab_install_okd_version }} to {{ _okd_lab_install_name }}
  command: oc adm -a /root/.secrets/okd-lab-pull-secret.json release mirror --insecure --from={{ _okd_lab_install_mirror_from }}:{{ okd_lab_install_okd_version }} --to={{ _okd_lab_quay_url }}/kubeadmin/{{ _okd_lab_install_name }} --to-release-image={{ _okd_lab_quay_url }}/kubeadmin/{{ _okd_lab_install_name }}:{{ okd_lab_install_okd_version }}
