---
- hosts: 10.0.0.2
  vars:
# required
    okd_lab_docker_ce: '19.03.12-3'
    okd_lab_docker_ce_cli: '19.03.12-3'
    okd_lab_containerd: '1.2.13-3.2'
    okd_lab_quay_version: 'qui-gon'

# optional
    okd_lab_artifactory_version: '7.6.1'
    okd_lab_gitlab_version: '13.0.7-ce.0'
    okd_lab_portainer_version: '1.24.0'
    okd_lab_keycloak_version: '10.0.2'

  gather_facts: no
  remote_user: root
  roles:
# required
    - ipxe
    - jq
    - docker
    - quay
# optional
    - gitlab
    - portainer
    - keycloak
    - artifactory
