---
- hosts: bastion
  vars:
    # Unique name of this installation
    okd_lab_install_name: '4-5-0-0-okd-2020-07-14-153706-ga'

    # OKD installation version
    okd_lab_install_okd_version: 4.5.0-0.okd-2020-07-14-153706-ga
    
    # Fedora CoreOS installation version and stream
    okd_lab_install_fcos_version: '32.20200615.3.0'
    okd_lab_install_fcos_stream: 'stable'

    # Download URL for stable oc 4 client
    okd_lab_install_okd_client_stable_url: 'https://github.com/openshift/okd/releases/download/4.4.0-0.okd-2020-05-23-055148-beta5/openshift-client-linux-4.4.0-0.okd-2020-05-23-055148-beta5.tar.gz'  

  gather_facts: no
  roles:
    - setup
    - fcos
    - mirror
    - installer
