---
- name: Merge pull secrets
  shell: "jq -s '{\"auths\": ( .[0].auths + .[1].auths ) }' /home/lab/okd-lab/.secrets/quay-pull-secret.json /home/lab/okd-lab/.secrets/redhat-pull-secret.json > /home/lab/okd-lab/.secrets/okd-lab-pull-secret.json"

