---
- name: Allow 9999/tcp in firewalld
  command: firewall-cmd --zone=public --permanent --add-port="9999/tcp"

- name: Reload firewall
  command: firewall-cmd --reload

- name: Create Directories
  file:
    path: '{{ item.dir }}'
    state: directory
  with_items:
    - { dir: '~/docker/portainer' }
    - { dir: '~/docker/mounts/portainer' }
    - { dir: '~/docker/mounts/portainer/data' }

- name: Publish docker-compose.yaml
  template: 
    src:  docker-compose.yaml.j2
    dest: ~/docker/portainer/docker-compose.yaml

- name: Start Portainer
  command: docker-compose up -d
  args:
    chdir: ~/docker/portainer
